spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:activitydb}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5671}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    ssl:
      enabled: ${RABBITMQ_SSL:true}

server:
  port: 8083

rabbitmq:
  exchange:
    name: fitness.exchange

activity:
  queue: activity.queue
  routingKey: activity.tracking

goals:
  queue: goals.queue
  routingKey: goals

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}